# Generated by Django 3.2.14 on 2022-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Contact Phone'),
        ),
    ]
